version: '3'

services:
  web:
    build: .
    image: ura_backend
    volumes:
      - .:/uClassify
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=127.0.0.1
      - DB_ENGINE=django.db.backends.sqlite3
      - DB_NAME=db.sqlite3
      - CELERY_BROKER_URL=amqp://guest:guest@localhost:5672//
    depends_on:
      - celery
      - rabbitmq

  rabbitmq:
    image: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

  celery:
    image: ura_backend
    entrypoint: ["celery", "-A", "uClassify", "worker", "-l", "INFO", "-P", "solo"]
    volumes:
      - .:/uClassify
    depends_on:
      - rabbitmq
