# Generated by Django 4.2.3 on 2023-08-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodeltask',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trainingmodeltask',
            name='is_done',
        ),
        migrations.AddField(
            model_name='customizedimageclassificationmodel',
            name='model_type',
            field=models.CharField(choices=[('ViT', 'Vision Transformer'), ('IV3', 'Inception V3'), ('RN2', 'ResNet V2 50'), ('MN2', 'MobileNet V2'), ('MN3', 'MobileNet V3')], default='IV3', max_length=3),
        ),
        migrations.AlterField(
            model_name='customizedimageclassificationmodel',
            name='model_path',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trainingmodeltask',
            name='task_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
